dataset_config:
  data_name: "dexdeform_folding"
  data_dir: "./data"            # data directory
  prep_data_dir: "./prep_data"  # preprocessed data directory
  device: "cuda:0"

  verbose: False

  n_his: 4
  n_future: 3
  
  randomness: 
    use: True 
    state_noise:
      train: 0.05
      valid: 0.0
      test: 0.0
      
  n_obj_ptcls: 1000


model_config:
  n_his: 4      # same as dataset config
  pstep: 3      # propagation steps
  latent_dim: 64
  cradius: 0.1
  nngbrs: 5


train_config:
  out_dir: "./dynamics"         # dynamics model output directory for saving checkpoints and loss logs
  phases: ["train", "valid"]
  num_workers: 8
  random_seed: 42
  verbose: False

  batch_size: 128 
  n_epochs: 100
  n_iters_per_epoch: 
    train: 1000
    valid: 100
  
  lr: 0.001
  log_interval: 50


rollout_config:
  out_dir: "./rollout"           # rollout output directory for saving results
  rollout_steps: 100
